server:
  port: 8080
spring:
  application:
    name: BMS
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 150618
  redis:
    host: 192.168.229.129
    database: 0
    password: 123456
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: -1ms
      shutdown-timeout: 100ms
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
